/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualkeybord;

import java.awt.AWTException;
import java.awt.RenderingHints;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rasika
 */
public class VirtualKeybord extends javax.swing.JFrame {

    /**
     * Creates new form VirtualKeybord
     */
    
    private Robot robot;
    public VirtualKeybord() {
        initComponents();
        boolean cpLockstate=Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        
        if(cpLockstate){
        
        capslockBtn.setSelected(true);
        }
        
        try {
            robot = new Robot();
        } catch (AWTException ex) {
            Logger.getLogger(VirtualKeybord.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private boolean shiftselected;
    
    private boolean ctrlselected;
    private boolean altselected;
    
    
    private void setCapitalletters(){
    
        aBtn.setText("A");
        bBtn.setText("B");
        cBtn.setText("C");
        dBtn.setText("D");
        eBtn.setText("E");
        fBtn.setText("F");
        gBtn.setText("G");
        hBtn.setText("H");
        iBtn.setText("I");
        jBtn.setText("J");
        kBtn.setText("K");
        lBtn.setText("L");
        mBtn.setText("M");
        nBtn.setText("N");
        oBtn.setText("O");
        pBtn.setText("P");
        qBtn.setText("Q");
        rBtn.setText("R");
        sBtn.setText("S");
        tBtn.setText("T");
        uBtn.setText("U");
        vBtn.setText("V");
        wBtn.setText("W");
        xBtn.setText("X");
        yBtn.setText("Y");
        zBtn.setText("Z");
         
   
   }
    
    private boolean setSimpleletters(){
    
    aBtn.setText("a");
        bBtn.setText("b");
        cBtn.setText("c");
        dBtn.setText("d");
        eBtn.setText("e");
        fBtn.setText("f");
        gBtn.setText("g");
        hBtn.setText("h");
        iBtn.setText("i");
        jBtn.setText("j");
        kBtn.setText("k");
        lBtn.setText("l");
        mBtn.setText("m");
        nBtn.setText("n");
        oBtn.setText("o");
        pBtn.setText("p");
        qBtn.setText("q");
        rBtn.setText("r");
        sBtn.setText("s");
        tBtn.setText("t");
        uBtn.setText("u");
        vBtn.setText("v");
        wBtn.setText("w");
        xBtn.setText("x");
        yBtn.setText("y");
        zBtn.setText("z");
        return false;
    
    
    }
    private void actionkeyControl(){
    
    if(shiftselected){
    
        shiftselected=false;
        robot.keyRelease(KeyEvent.VK_SHIFT);
        setSimpleletters();
        lshiftBtn.setSelected(false);
        rshiftBtn.setSelected(false);
                
    }
    if (ctrlselected){
        
        ctrlselected=false;
        robot.keyRelease(KeyEvent.VK_CONTROL);
        lctrlBtn.setSelected(false);
        rtrlBtn.setSelected(false);
    }
    
    if (altselected){
    
        altselected=false;
        robot.keyRelease(KeyEvent.VK_ALT);
        laltBtn.setSelected(false);
        
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
            
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        zeoBtn = new javax.swing.JButton();
        minusBtn = new javax.swing.JButton();
        equalBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tabBtn = new javax.swing.JButton();
        qBtn = new javax.swing.JButton();
        wBtn = new javax.swing.JButton();
        eBtn = new javax.swing.JButton();
        rBtn = new javax.swing.JButton();
        tBtn = new javax.swing.JButton();
        yBtn = new javax.swing.JButton();
        uBtn = new javax.swing.JButton();
        iBtn = new javax.swing.JButton();
        oBtn = new javax.swing.JButton();
        pBtn = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        aBtn = new javax.swing.JButton();
        sBtn = new javax.swing.JButton();
        dBtn = new javax.swing.JButton();
        fBtn = new javax.swing.JButton();
        gBtn = new javax.swing.JButton();
        hBtn = new javax.swing.JButton();
        jBtn = new javax.swing.JButton();
        kBtn = new javax.swing.JButton();
        lBtn = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        backspaceBtn = new javax.swing.JToggleButton();
        rshiftBtn = new javax.swing.JToggleButton();
        capslockBtn = new javax.swing.JToggleButton();
        lshiftBtn = new javax.swing.JToggleButton();
        lctrlBtn = new javax.swing.JToggleButton();
        enterBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        zBtn = new javax.swing.JButton();
        xBtn = new javax.swing.JButton();
        cBtn = new javax.swing.JButton();
        vBtn = new javax.swing.JButton();
        bBtn = new javax.swing.JButton();
        nBtn = new javax.swing.JButton();
        mBtn = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        spaceBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lwinBtn = new javax.swing.JButton();
        laltBtn = new javax.swing.JToggleButton();
        optionBtn = new javax.swing.JButton();
        rwinBtn = new javax.swing.JButton();
        rtrlBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jButton13.setText("~ `");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton13);

        oneBtn.setText("1 !");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });
        jPanel3.add(oneBtn);

        twoBtn.setText("2 @");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        jPanel3.add(twoBtn);

        threeBtn.setText("3 #");
        jPanel3.add(threeBtn);

        fourBtn.setText("4 $");
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });
        jPanel3.add(fourBtn);

        fiveBtn.setText("5 %");
        jPanel3.add(fiveBtn);

        sixBtn.setText("6 ^");
        jPanel3.add(sixBtn);

        sevenBtn.setText("7 &");
        jPanel3.add(sevenBtn);

        eightBtn.setText("8 *");
        jPanel3.add(eightBtn);

        nineBtn.setText("9 (");
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });
        jPanel3.add(nineBtn);

        zeoBtn.setText("0 )");
        jPanel3.add(zeoBtn);

        minusBtn.setText("- _");
        jPanel3.add(minusBtn);

        equalBtn.setText("=");
        equalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalBtnActionPerformed(evt);
            }
        });
        jPanel3.add(equalBtn);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 50));

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        tabBtn.setText("TAB");
        tabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabBtnActionPerformed(evt);
            }
        });
        jPanel4.add(tabBtn);

        qBtn.setText("Q");
        qBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qBtnActionPerformed(evt);
            }
        });
        jPanel4.add(qBtn);

        wBtn.setText("W");
        wBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wBtnActionPerformed(evt);
            }
        });
        jPanel4.add(wBtn);

        eBtn.setText("E");
        jPanel4.add(eBtn);

        rBtn.setText("R");
        rBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnActionPerformed(evt);
            }
        });
        jPanel4.add(rBtn);

        tBtn.setText("T");
        jPanel4.add(tBtn);

        yBtn.setText("Y");
        yBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yBtnActionPerformed(evt);
            }
        });
        jPanel4.add(yBtn);

        uBtn.setText("U");
        jPanel4.add(uBtn);

        iBtn.setText("I");
        jPanel4.add(iBtn);

        oBtn.setText("O");
        jPanel4.add(oBtn);

        pBtn.setText("P");
        jPanel4.add(pBtn);

        jButton36.setText("{");
        jPanel4.add(jButton36);

        jButton50.setText("}");
        jPanel4.add(jButton50);

        jButton51.setText("}");
        jPanel4.add(jButton51);

        jButton60.setText("| \\");
            jPanel4.add(jButton60);

            jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 920, 50));

            jPanel5.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

            aBtn.setText("A");
            aBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    aBtnActionPerformed(evt);
                }
            });
            jPanel5.add(aBtn);

            sBtn.setText("S");
            sBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    sBtnActionPerformed(evt);
                }
            });
            jPanel5.add(sBtn);

            dBtn.setText("D");
            dBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    dBtnActionPerformed(evt);
                }
            });
            jPanel5.add(dBtn);

            fBtn.setText("F");
            fBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fBtnActionPerformed(evt);
                }
            });
            jPanel5.add(fBtn);

            gBtn.setText("G");
            gBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    gBtnActionPerformed(evt);
                }
            });
            jPanel5.add(gBtn);

            hBtn.setText("H");
            hBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    hBtnActionPerformed(evt);
                }
            });
            jPanel5.add(hBtn);

            jBtn.setText("J");
            jPanel5.add(jBtn);

            kBtn.setText("K");
            jPanel5.add(kBtn);

            lBtn.setText("L");
            jPanel5.add(lBtn);

            jButton47.setText(": ;");
            jPanel5.add(jButton47);

            jButton48.setText("\" '");
            jPanel5.add(jButton48);

            jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 750, 50));

            backspaceBtn.setText("BACKSPACE");
            jPanel1.add(backspaceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 170, 50));

            rshiftBtn.setText("SHIFT");
            jPanel1.add(rshiftBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 120, 50));

            capslockBtn.setText("CAPSLOCK");
            capslockBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    capslockBtnActionPerformed(evt);
                }
            });
            jPanel1.add(capslockBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 50));

            lshiftBtn.setText("SHIFT");
            lshiftBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    lshiftBtnActionPerformed(evt);
                }
            });
            jPanel1.add(lshiftBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 50));

            lctrlBtn.setText("CTRL");
            lctrlBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    lctrlBtnActionPerformed(evt);
                }
            });
            jPanel1.add(lctrlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, 50));

            enterBtn.setText("ENTER");
            jPanel1.add(enterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 80, 50));

            jPanel7.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

            zBtn.setText("Z");
            jPanel7.add(zBtn);

            xBtn.setText("X");
            jPanel7.add(xBtn);

            cBtn.setText("C");
            cBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cBtnActionPerformed(evt);
                }
            });
            jPanel7.add(cBtn);

            vBtn.setText("V");
            vBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    vBtnActionPerformed(evt);
                }
            });
            jPanel7.add(vBtn);

            bBtn.setText("B");
            jPanel7.add(bBtn);

            nBtn.setText("N");
            jPanel7.add(nBtn);

            mBtn.setText("M");
            jPanel7.add(mBtn);

            jButton69.setText("< ,");
            jPanel7.add(jButton69);

            jButton70.setText("> .");
            jPanel7.add(jButton70);

            jButton71.setText("? /");
            jPanel7.add(jButton71);

            jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 670, 50));

            spaceBtn.setText("SPACE");
            spaceBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    spaceBtnActionPerformed(evt);
                }
            });
            jPanel1.add(spaceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 460, 50));

            jPanel8.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

            lwinBtn.setText("WIN");
            lwinBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    lwinBtnActionPerformed(evt);
                }
            });
            jPanel8.add(lwinBtn);

            laltBtn.setText("ALT");
            laltBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    laltBtnActionPerformed(evt);
                }
            });
            jPanel8.add(laltBtn);

            jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 130, 50));

            optionBtn.setText("OPTION");
            optionBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    optionBtnActionPerformed(evt);
                }
            });
            jPanel1.add(optionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 80, 50));

            rwinBtn.setText("WIN");
            rwinBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    rwinBtnActionPerformed(evt);
                }
            });
            jPanel1.add(rwinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 60, 50));

            rtrlBtn.setText("CTRL");
            jPanel1.add(rtrlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 80, 50));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoBtnActionPerformed

    private void wBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_W);
        robot.keyRelease(KeyEvent.VK_W);
        actionkeyControl();
    }//GEN-LAST:event_wBtnActionPerformed

    private void dBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_D);
        robot.keyRelease(KeyEvent.VK_D);
        actionkeyControl();
    }//GEN-LAST:event_dBtnActionPerformed

    private void rBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_R);
        robot.keyRelease(KeyEvent.VK_R);
        actionkeyControl();
    }//GEN-LAST:event_rBtnActionPerformed

    private void yBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_Y);
        robot.keyRelease(KeyEvent.VK_Y);
        actionkeyControl();
    }//GEN-LAST:event_yBtnActionPerformed

    private void sBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_S);
        robot.keyRelease(KeyEvent.VK_S);
        actionkeyControl();
    }//GEN-LAST:event_sBtnActionPerformed

    private void fBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_F);
        robot.keyRelease(KeyEvent.VK_F);
                actionkeyControl();// TODO add your handling code here:

    }//GEN-LAST:event_fBtnActionPerformed

    private void gBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_G);
        robot.keyRelease(KeyEvent.VK_G);
                actionkeyControl();// TODO add your handling code here:

    }//GEN-LAST:event_gBtnActionPerformed

    private void hBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_H);
        robot.keyRelease(KeyEvent.VK_H);
        actionkeyControl();
    }//GEN-LAST:event_hBtnActionPerformed

    private void equalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_EQUALS);
        robot.keyRelease(KeyEvent.VK_EQUALS);
        actionkeyControl();
    }//GEN-LAST:event_equalBtnActionPerformed

    private void cBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_C);
        robot.keyRelease(KeyEvent.VK_C);
        actionkeyControl();
    }//GEN-LAST:event_cBtnActionPerformed

    private void vBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_V);
        robot.keyRelease(KeyEvent.VK_V);
        actionkeyControl();
    }//GEN-LAST:event_vBtnActionPerformed

    private void qBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qBtnActionPerformed

    robot.keyPress(KeyEvent.VK_Q);
        robot.keyRelease(KeyEvent.VK_Q);  
        actionkeyControl();// TODO add your handling code here:
    }//GEN-LAST:event_qBtnActionPerformed

    private void aBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_A);
        robot.keyRelease(KeyEvent.VK_A);
                actionkeyControl();// TODO add your handling code here:

    }//GEN-LAST:event_aBtnActionPerformed

    private void spaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceBtnActionPerformed
            robot.keyPress(KeyEvent.VK_SPACE);
        robot.keyRelease(KeyEvent.VK_SPACE);
        actionkeyControl();// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceBtnActionPerformed

    private void optionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_optionBtnActionPerformed

    private void rwinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rwinBtnActionPerformed
        // TODO add your handling code here:
        robot.keyPress(KeyEvent.VK_WINDOWS);
        robot.keyRelease(KeyEvent.VK_WINDOWS);
                actionkeyControl();// TODO add your handling code here:

    }//GEN-LAST:event_rwinBtnActionPerformed

    private void tabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabBtnActionPerformed
                // TODO add your handling code here:
                
                robot.keyPress(KeyEvent.VK_TAB);
                robot.keyRelease(KeyEvent.VK_TAB);
                        actionkeyControl();// TODO add your handling code here:

    }//GEN-LAST:event_tabBtnActionPerformed

    private void capslockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capslockBtnActionPerformed
        // TODO add your handling code here:
        if(capslockBtn.isSelected()){
        
        robot.keyPress(KeyEvent.VK_CAPS_LOCK);
        robot.keyRelease(KeyEvent.VK_CAPS_LOCK);
        }else{
        
        robot.keyPress(KeyEvent.VK_CAPS_LOCK);
        robot.keyRelease(KeyEvent.VK_CAPS_LOCK);
        
        }
        
        
        
    }//GEN-LAST:event_capslockBtnActionPerformed

    private void lshiftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lshiftBtnActionPerformed
        // TODO add your handling code here:
        
        if(lshiftBtn.isSelected()){
        
        shiftselected=true;
        robot.keyPress(KeyEvent.VK_SHIFT);
        rshiftBtn.setSelected(true);
        setCapitalletters();
        
        }else{
        
        shiftselected=false;
        robot.keyRelease(KeyEvent.VK_SHIFT);
        rshiftBtn.setSelected(false);
        setSimpleletters();
        
        }
    }//GEN-LAST:event_lshiftBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nineBtnActionPerformed

    private void lwinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lwinBtnActionPerformed
        // TODO add your handling code here:
        
        robot.keyPress(KeyEvent.VK_WINDOWS);
        robot.keyRelease(KeyEvent.VK_WINDOWS);
                actionkeyControl();// TODO add your handling code here:

    }//GEN-LAST:event_lwinBtnActionPerformed

    private void lctrlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lctrlBtnActionPerformed
       
        if(lctrlBtn.isSelected()){
        
        ctrlselected=true;
        robot.keyPress(KeyEvent.VK_CONTROL);
            lctrlBtn.setSelected(true);
        
        
        }else{
        
            ctrlselected=false;
            robot.keyRelease(KeyEvent.VK_CONTROL);
            lctrlBtn.setSelected(false);
        
        }
    }//GEN-LAST:event_lctrlBtnActionPerformed

    private void laltBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laltBtnActionPerformed
        // TODO add your handling code here:
        
        if(laltBtn.isSelected()){
            altselected=true;
        robot.keyPress(KeyEvent.VK_ALT);
        //laltBtn.setSelected(true);
        }else{
        
        altselected=false;
        robot.keyRelease(KeyEvent.VK_ALT);
        
        }
        
            
        
    }//GEN-LAST:event_laltBtnActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       
    }//GEN-LAST:event_jButton13ActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
       
        robot.keyPress(KeyEvent.VK_NUMPAD1);
        robot.keyPress(KeyEvent.VK_NUMPAD1);
    }//GEN-LAST:event_oneBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualKeybord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualKeybord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualKeybord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualKeybord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VirtualKeybord().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aBtn;
    private javax.swing.JButton bBtn;
    private javax.swing.JToggleButton backspaceBtn;
    private javax.swing.JButton cBtn;
    private javax.swing.JToggleButton capslockBtn;
    private javax.swing.JButton dBtn;
    private javax.swing.JButton eBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JButton enterBtn;
    private javax.swing.JButton equalBtn;
    private javax.swing.JButton fBtn;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton gBtn;
    private javax.swing.JButton hBtn;
    private javax.swing.JButton iBtn;
    private javax.swing.JButton jBtn;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton kBtn;
    private javax.swing.JButton lBtn;
    private javax.swing.JToggleButton laltBtn;
    private javax.swing.JToggleButton lctrlBtn;
    private javax.swing.JToggleButton lshiftBtn;
    private javax.swing.JButton lwinBtn;
    private javax.swing.JButton mBtn;
    private javax.swing.JButton minusBtn;
    private javax.swing.JButton nBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton optionBtn;
    private javax.swing.JButton pBtn;
    private javax.swing.JButton qBtn;
    private javax.swing.JButton rBtn;
    private javax.swing.JToggleButton rshiftBtn;
    private javax.swing.JToggleButton rtrlBtn;
    private javax.swing.JButton rwinBtn;
    private javax.swing.JButton sBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton spaceBtn;
    private javax.swing.JButton tBtn;
    private javax.swing.JButton tabBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JButton uBtn;
    private javax.swing.JButton vBtn;
    private javax.swing.JButton wBtn;
    private javax.swing.JButton xBtn;
    private javax.swing.JButton yBtn;
    private javax.swing.JButton zBtn;
    private javax.swing.JButton zeoBtn;
    // End of variables declaration//GEN-END:variables
}
